/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as draftErc20PermitUpgradeableSol from "./draft-ERC20PermitUpgradeable.sol";
import type * as draftIerc20PermitUpgradeableSol from "./draft-IERC20PermitUpgradeable.sol";

export type { draftErc20PermitUpgradeableSol };

export type { draftIerc20PermitUpgradeableSol };
export type { ERC20SnapshotUpgradeable } from "./ERC20SnapshotUpgradeable";
export type { IERC20MetadataUpgradeable } from "./IERC20MetadataUpgradeable";
