/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IBaalStore,
  IBaalStoreInterface,
} from "../../../../../contracts/fixtures/Baal/interfaces/IBaalStore";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "proposalId",
        type: "uint32",
      },
    ],
    name: "getMemberVoted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "getProposal",
    outputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "id",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "prevProposalId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "votingStarts",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "votingEnds",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "graceEnds",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiration",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "baalGas",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "yesVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "noVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxTotalSharesAndLootAtVote",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxTotalSharesAtSponsor",
            type: "uint256",
          },
          {
            internalType: "bool[4]",
            name: "status",
            type: "bool[4]",
          },
          {
            internalType: "address",
            name: "sponsor",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "proposalDataHash",
            type: "bytes32",
          },
        ],
        internalType: "struct BaalTypes.Proposal",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "getVotingNonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "incrementVotingNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "proposalId",
        type: "uint32",
      },
      {
        internalType: "bool",
        name: "voted",
        type: "bool",
      },
    ],
    name: "setMemberVoted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "id",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "prevProposalId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "votingStarts",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "votingEnds",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "graceEnds",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expiration",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "baalGas",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "yesVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "noVotes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxTotalSharesAndLootAtVote",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxTotalSharesAtSponsor",
            type: "uint256",
          },
          {
            internalType: "bool[4]",
            name: "status",
            type: "bool[4]",
          },
          {
            internalType: "address",
            name: "sponsor",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "proposalDataHash",
            type: "bytes32",
          },
        ],
        internalType: "struct BaalTypes.Proposal",
        name: "proposal",
        type: "tuple",
      },
    ],
    name: "setProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "setVotingNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBaalStore__factory {
  static readonly abi = _abi;
  static createInterface(): IBaalStoreInterface {
    return new utils.Interface(_abi) as IBaalStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaalStore {
    return new Contract(address, _abi, signerOrProvider) as IBaalStore;
  }
}
