/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IBaalSummoner,
  IBaalSummonerInterface,
} from "../../../../../contracts/fixtures/Baal/interfaces/IBaalSummoner";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_moduleAddr",
        type: "address",
      },
    ],
    name: "deployAndSetupSafe",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lootSingleton",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sharesSingleton",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initializationParams",
        type: "bytes",
      },
      {
        internalType: "bytes[]",
        name: "initializationActions",
        type: "bytes[]",
      },
      {
        internalType: "uint256",
        name: "_saltNonce",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "referrer",
        type: "bytes32",
      },
    ],
    name: "summonBaalFromReferrer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IBaalSummoner__factory {
  static readonly abi = _abi;
  static createInterface(): IBaalSummonerInterface {
    return new utils.Interface(_abi) as IBaalSummonerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaalSummoner {
    return new Contract(address, _abi, signerOrProvider) as IBaalSummoner;
  }
}
