/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface IBaalAdvTokenSummonerInterface extends utils.Interface {
  functions: {
    "summonBaalFromReferrer(uint256,bytes,bytes,bytes[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "summonBaalFromReferrer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "summonBaalFromReferrer",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "summonBaalFromReferrer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IBaalAdvTokenSummoner extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBaalAdvTokenSummonerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    summonBaalFromReferrer(
      _saltNonce: PromiseOrValue<BigNumberish>,
      _initializationMintParams: PromiseOrValue<BytesLike>,
      _initializationTokenParams: PromiseOrValue<BytesLike>,
      _postInitializationActions: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  summonBaalFromReferrer(
    _saltNonce: PromiseOrValue<BigNumberish>,
    _initializationMintParams: PromiseOrValue<BytesLike>,
    _initializationTokenParams: PromiseOrValue<BytesLike>,
    _postInitializationActions: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    summonBaalFromReferrer(
      _saltNonce: PromiseOrValue<BigNumberish>,
      _initializationMintParams: PromiseOrValue<BytesLike>,
      _initializationTokenParams: PromiseOrValue<BytesLike>,
      _postInitializationActions: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    summonBaalFromReferrer(
      _saltNonce: PromiseOrValue<BigNumberish>,
      _initializationMintParams: PromiseOrValue<BytesLike>,
      _initializationTokenParams: PromiseOrValue<BytesLike>,
      _postInitializationActions: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    summonBaalFromReferrer(
      _saltNonce: PromiseOrValue<BigNumberish>,
      _initializationMintParams: PromiseOrValue<BytesLike>,
      _initializationTokenParams: PromiseOrValue<BytesLike>,
      _postInitializationActions: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
