"use client";

import { Footer } from "./Footer";
import { Header } from "./Header";
import "./global.css";
import { Providers } from "./providers";

// export const metadata = {
//   title: "Welcome to frontend",
//   description: "Generated by create-nx-workspace",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="body">
        <Providers>
          <Header />
          <main style={{ maxWidth: "100vw", flexGrow: 1 }}>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
