"use client";

import { Header } from "./Header";
import "./global.css";
import { Providers } from "./providers";

// export const metadata = {
//   title: "Welcome to frontend",
//   description: "Generated by create-nx-workspace",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
