/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as fixtures from "./fixtures";
import type * as mock from "./mock";
import type * as shaman from "./shaman";

export type { fixtures };

export type { mock };

export type { shaman };
