/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  DelegationEIP712Upgradeable,
  DelegationEIP712UpgradeableInterface,
} from "../../../../../contracts/fixtures/Baal/utils/DelegationEIP712Upgradeable";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class DelegationEIP712Upgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): DelegationEIP712UpgradeableInterface {
    return new utils.Interface(_abi) as DelegationEIP712UpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DelegationEIP712Upgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DelegationEIP712Upgradeable;
  }
}
