name: "EVM-SUBGRAPH"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "evm/subgraph/**"
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "evm/subgraph/**"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"        
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          # cache: "yarn"
          node-version: "18"

      - name: "Install the dependencies"
        run: "yarn install --immutable"
        
      - name: "Generate types and test mappings"
        run: "yarn nx run subgraph:codegen && yarn nx run subgraph:test"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
